backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: 'affordables'
    label: 'S106 Affordable Homes'
    extension: 'json'    

    files:
        - label: 'Affordables'
          name: 'affordables'
          file: 'content/schemes.json'
          fields:
              - { label: 'Ref', name: 'ref', widget: 'string' }
              - { label: 'Address', name: 'address', widget: 'datetime' }
              - { label: 'Date completed', name: 'completion', widget: 'datetime' }
              - { label: 'Post Code', name: 'postcode', widget: 'string' }
