backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: 'affordables'
    label: 'S106 Affordable Homes'
    folder: 'content/schemes.json'
    create: true
    slug: 'index'
    media_folder: ''
    public_folder: ''
    path: '{{title}}/index'
    editor:
      preview: false
    fields:
      - { label: 'Ref', name: 'ref', widget: 'string' }
      - { label: 'Address', name: 'address', widget: 'datetime' }
      - { label: 'Date completed', name: 'completion', widget: 'datetime' }
      - { label: 'Post Code', name: 'postcode', widget: 'string' }
